export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_SUCCESS = "GET_PRODUCT_BY_ID_SUCCESS";
export const GET_PRODUCT_BY_ID_FAIL = "GET_PRODUCT_BY_ID_FAIL";

export const GET_PRODUCTS_BULK_REQUEST = "GET_PRODUCTS_BULK_REQUEST";
export const GET_PRODUCTS_BULK_SUCCESS = "GET_PRODUCTS_BULK_SUCCESS";
export const GET_PRODUCTS_BULK_FAIL = "GET_PRODUCTS_BULK_FAIL";